import type { AgendaEvent, AgendaEventInput, RecurringSchedule, RecurringScheduleInput, VersionedAgendaEntity, Weekday } from '../domain/agenda.ts';
import { AgendaConflictError, AgendaNotFoundError, type AgendaAdminRepository, type AuditAction } from './AgendaAdminRepository.ts';

type ScheduleRow = { id:string; title:string; weekday:number; start_time:string; end_time:string|null; location_name:string; location_address:string|null; description:string|null; active:number; sort_order:number; updated_at:string };
type EventRow = { id:string; title:string; start_date:string; end_date:string|null; start_time:string|null; end_time:string|null; location_name:string; location_address:string|null; summary:string|null; description:string|null; image_key:string|null; status:AgendaEvent['status']; source_kind:AgendaEvent['source']['kind']; bulletin_id:string|null; bulletin_item_id:string|null; updated_at:string };
const optional = <T>(value:T|null) => value === null ? undefined : value;
const scheduleFrom = (r:ScheduleRow):VersionedAgendaEntity<RecurringSchedule> => ({ id:r.id,title:r.title,weekday:r.weekday as Weekday,startTime:r.start_time,endTime:optional(r.end_time),location:{name:r.location_name,address:optional(r.location_address)},description:optional(r.description),active:r.active===1,sortOrder:r.sort_order,updatedAt:r.updated_at });
const eventFrom = (r:EventRow):VersionedAgendaEntity<AgendaEvent> => ({ id:r.id,title:r.title,startDate:r.start_date,endDate:optional(r.end_date),startTime:optional(r.start_time),endTime:optional(r.end_time),location:{name:r.location_name,address:optional(r.location_address)},summary:optional(r.summary),description:optional(r.description),image:optional(r.image_key),status:r.status,source:{kind:r.source_kind,bulletinId:optional(r.bulletin_id),bulletinItemId:optional(r.bulletin_item_id)},updatedAt:r.updated_at });
const stamp = () => { const timestamp=new Date().toISOString(); return {timestamp,version:`${timestamp}#${crypto.randomUUID()}`}; };
const audit = (db:D1Database, actor:string, action:AuditAction, type:'recurring_schedule'|'agenda_event', id:string, timestamp:string) => db.prepare("INSERT INTO admin_audit_log (id, actor, action, entity_type, entity_id, timestamp, metadata_json) SELECT ?, ?, ?, ?, ?, ?, '{}' WHERE changes() = 1").bind(`audit-${crypto.randomUUID()}`, actor, action, type, id, timestamp);

export class D1AgendaAdminRepository implements AgendaAdminRepository {
  private readonly db:D1Database;
  constructor(db:D1Database) { this.db=db; }
  async listRecurring() { const {results}=await this.db.prepare('SELECT * FROM recurring_schedules ORDER BY sort_order, weekday, start_time').all<ScheduleRow>(); return results.map(scheduleFrom); }
  async listEvents() { const {results}=await this.db.prepare('SELECT * FROM agenda_events ORDER BY start_date DESC, COALESCE(start_time,\'00:00\'), id').all<EventRow>(); return results.map(eventFrom); }
  private async schedule(id:string) { const row=await this.db.prepare('SELECT * FROM recurring_schedules WHERE id = ?').bind(id).first<ScheduleRow>(); if(!row) throw new AgendaNotFoundError('Programação não encontrada.'); return scheduleFrom(row); }
  private async event(id:string) { const row=await this.db.prepare('SELECT * FROM agenda_events WHERE id = ?').bind(id).first<EventRow>(); if(!row) throw new AgendaNotFoundError('Evento não encontrado.'); return eventFrom(row); }
  async createRecurring(input:RecurringScheduleInput, actor:string) { const id=input.id || `agenda-${crypto.randomUUID()}`; const {timestamp,version}=stamp(); const insert=this.db.prepare('INSERT INTO recurring_schedules (id,title,weekday,start_time,end_time,location_name,location_address,description,active,sort_order,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,input.title,input.weekday,input.startTime,input.endTime||null,input.location.name,input.location.address||null,input.description||null,input.active?1:0,input.sortOrder||0,timestamp,version); await this.db.batch([insert,audit(this.db,actor,'create','recurring_schedule',id,timestamp)]); return this.schedule(id); }
  async updateRecurring(id:string,input:RecurringScheduleInput,expected:string,actor:string) { const {timestamp,version}=stamp(); const current=await this.schedule(id); const action:AuditAction=current.active!==input.active ? (input.active?'activate':'deactivate') : 'update'; const update=this.db.prepare('UPDATE recurring_schedules SET title=?,weekday=?,start_time=?,end_time=?,location_name=?,location_address=?,description=?,active=?,sort_order=?,updated_at=? WHERE id=? AND updated_at=?').bind(input.title,input.weekday,input.startTime,input.endTime||null,input.location.name,input.location.address||null,input.description||null,input.active?1:0,input.sortOrder||0,version,id,expected); const result=await this.db.batch([update,audit(this.db,actor,action,'recurring_schedule',id,timestamp)]); if((result[0].meta.changes||0)!==1) throw new AgendaConflictError('Este registro foi alterado por outra pessoa. Recarregue e tente novamente.'); return this.schedule(id); }
  async createEvent(input:AgendaEventInput,actor:string) { const id=input.id||`agenda-${crypto.randomUUID()}`; const {timestamp,version}=stamp(); const insert=this.db.prepare("INSERT INTO agenda_events (id,title,start_date,end_date,start_time,end_time,location_name,location_address,summary,description,image_key,status,source_kind,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?, 'manual',?,?)").bind(id,input.title,input.startDate,input.endDate||null,input.startTime||null,input.endTime||null,input.location.name,input.location.address||null,input.summary||null,input.description||null,input.image||null,input.status,timestamp,version); const action:AuditAction=input.status==='published'?'publish':input.status==='cancelled'?'cancel':'create'; await this.db.batch([insert,audit(this.db,actor,action,'agenda_event',id,timestamp)]); return this.event(id); }
  async updateEvent(id:string,input:AgendaEventInput,expected:string,actor:string) { const {timestamp,version}=stamp(); const current=await this.event(id); const action:AuditAction=current.status!==input.status?(input.status==='published'?'publish':input.status==='cancelled'?'cancel':'update'):'update'; const update=this.db.prepare("UPDATE agenda_events SET title=?,start_date=?,end_date=?,start_time=?,end_time=?,location_name=?,location_address=?,summary=?,description=?,image_key=?,status=?,updated_at=? WHERE id=? AND updated_at=? AND source_kind='manual'").bind(input.title,input.startDate,input.endDate||null,input.startTime||null,input.endTime||null,input.location.name,input.location.address||null,input.summary||null,input.description||null,input.image||null,input.status,version,id,expected); const result=await this.db.batch([update,audit(this.db,actor,action,'agenda_event',id,timestamp)]); if((result[0].meta.changes||0)!==1) throw new AgendaConflictError('Este registro foi alterado por outra pessoa. Recarregue e tente novamente.'); return this.event(id); }
}
