import { normalizeBulletin, slugifyBulletin, suggestNextSunday, type Bulletin, type BulletinActivity, type BulletinInput, type RichTextDocument, type VersionedBulletin } from '../domain/bulletin.ts';
import type { BibleReference } from '../domain/study.ts';
import { BulletinAdminConflictError, BulletinAdminNotFoundError, BulletinNumberConflictError, type BulletinAdminRepository } from './BulletinAdminRepository.ts';

type ParentRow={id:string;number:number;slug:string;date:string;template_id:string;status:Bulletin['status'];pastoral_title:string;pastoral_body_json:string;bible_book:string|null;bible_chapter:number|null;bible_verse_start:number|null;bible_verse_end:number|null;published_at:string|null;deleted_at:string|null;pdf_storage_key:string|null;pdf_generated_at:string|null;pdf_page_count:number|null;created_at:string;updated_at:string};
type AnnouncementRow={id:string;title:string;content_json:string;image_key:string|null;agenda_event_id:string|null;sort_order:number};
type ActivityRow={id:string;text:string;start_date:string|null;end_date:string|null;start_time:string|null;end_time:string|null;location_name:string|null;location_address:string|null;description:string|null;agenda_event_id:string|null;sort_order:number};
type BirthdayRow={id:string;name:string;date:string;source:'manual'|'member';member_id:string|null;sort_order:number};
type DiaconalRow={id:string;date:string;responsible_json:string;sort_order:number};
type ReadingRow={id:string;day:string;reference_text:string;bible_book:string|null;bible_chapter:number|null;bible_verse_start:number|null;bible_verse_end:number|null;sort_order:number};
type BlockRow={block_json:string;sort_order:number};
const optional=<T>(value:T|null)=>value===null?undefined:value;
const parse=<T>(value:string)=>JSON.parse(value) as T;
const reference=(book:string|null,chapter:number|null,start:number|null,end:number|null):BibleReference|undefined=>book&&chapter!==null&&start!==null?{book,chapter,verseStart:start,verseEnd:optional(end)}:undefined;
const stamp=()=>{const timestamp=new Date().toISOString();return{timestamp,version:`${timestamp}#${crypto.randomUUID()}`}};
const audit=(db:D1Database,actor:string,action:string,id:string,timestamp:string,metadata:Record<string,unknown>={})=>db.prepare("INSERT INTO admin_audit_log (id,actor,action,entity_type,entity_id,timestamp,metadata_json) VALUES (?,?,?,'bulletin',?,?,?)").bind(`audit-${crypto.randomUUID()}`,actor,action,id,timestamp,JSON.stringify(metadata));
const isUnique=(error:unknown)=>error instanceof Error&&/UNIQUE constraint failed/.test(error.message);

export class D1BulletinAdminRepository implements BulletinAdminRepository {
  private readonly db:D1Database;
  constructor(db:D1Database){this.db=db;}
  private async hydrate(parent:ParentRow):Promise<VersionedBulletin>{
    const [announcements,activities,birthdays,diaconal,readings,blocks]=await Promise.all([
      this.db.prepare('SELECT * FROM bulletin_announcements WHERE bulletin_id=? ORDER BY sort_order,id').bind(parent.id).all<AnnouncementRow>(),
      this.db.prepare('SELECT * FROM bulletin_activities WHERE bulletin_id=? ORDER BY sort_order,id').bind(parent.id).all<ActivityRow>(),
      this.db.prepare('SELECT * FROM bulletin_birthdays WHERE bulletin_id=? ORDER BY sort_order,id').bind(parent.id).all<BirthdayRow>(),
      this.db.prepare('SELECT * FROM bulletin_diaconal_schedule WHERE bulletin_id=? ORDER BY sort_order,id').bind(parent.id).all<DiaconalRow>(),
      this.db.prepare('SELECT * FROM bulletin_weekly_readings WHERE bulletin_id=? ORDER BY sort_order,id').bind(parent.id).all<ReadingRow>(),
      this.db.prepare('SELECT * FROM bulletin_blocks WHERE bulletin_id=? ORDER BY sort_order,id').bind(parent.id).all<BlockRow>(),
    ]);
    const input:BulletinInput={id:parent.id,slug:parent.slug,number:parent.number,date:parent.date,templateId:parent.template_id,status:parent.status,pastoral:{title:parent.pastoral_title,body:parse<RichTextDocument>(parent.pastoral_body_json),bibleReference:reference(parent.bible_book,parent.bible_chapter,parent.bible_verse_start,parent.bible_verse_end)},announcements:announcements.results.map(r=>({id:r.id,title:r.title,content:parse(r.content_json),image:optional(r.image_key),agendaEventId:optional(r.agenda_event_id),sortOrder:r.sort_order})),monthActivities:activities.results.map(r=>({id:r.id,text:r.text,startDate:optional(r.start_date),endDate:optional(r.end_date),startTime:optional(r.start_time),endTime:optional(r.end_time),locationName:optional(r.location_name),locationAddress:optional(r.location_address),description:optional(r.description),agendaEventId:optional(r.agenda_event_id),sortOrder:r.sort_order})),birthdays:birthdays.results.map(r=>({id:r.id,name:r.name,date:r.date,source:r.source,memberId:optional(r.member_id),sortOrder:r.sort_order})),diaconalSchedule:diaconal.results.map(r=>({id:r.id,date:r.date,responsible:parse(r.responsible_json),sortOrder:r.sort_order})),weeklyReadings:readings.results.map(r=>({id:r.id,day:r.day,referenceText:r.reference_text,reference:reference(r.bible_book,r.bible_chapter,r.bible_verse_start,r.bible_verse_end),sortOrder:r.sort_order})),additionalBlocks:blocks.results.map(r=>parse(r.block_json)),publishedAt:optional(parent.published_at),deletedAt:optional(parent.deleted_at),pdf:parent.pdf_storage_key&&parent.pdf_generated_at&&parent.pdf_page_count===2?{storageKey:parent.pdf_storage_key,generatedAt:parent.pdf_generated_at,pageCount:2}:undefined};
    return {...normalizeBulletin(input),createdAt:parent.created_at,updatedAt:parent.updated_at};
  }
  private async parent(id:string){const row=await this.db.prepare('SELECT * FROM bulletins WHERE id=?').bind(id).first<ParentRow>();if(!row)throw new BulletinAdminNotFoundError('Boletim não encontrado.');return row;}
  async list(){const {results}=await this.db.prepare('SELECT * FROM bulletins ORDER BY number DESC,date DESC').all<ParentRow>();return Promise.all(results.map(row=>this.hydrate(row)));}
  async find(id:string){return this.hydrate(await this.parent(id));}
  async suggestions(){const row=await this.db.prepare("SELECT COALESCE(MAX(number),0)+1 AS number FROM bulletins").first<{number:number}>();return{number:row?.number||1,date:suggestNextSunday(),templateId:'iprc-padrao'};}
  private eventInsert(activity:BulletinActivity,bulletinId:string,timestamp:string){if(!activity.publishToAgenda||!activity.agendaEventDraft)return null;const id=`agenda-${crypto.randomUUID()}`,draft=activity.agendaEventDraft;activity.agendaEventId=id;activity.publishToAgenda=false;activity.agendaEventDraft=undefined;return this.db.prepare("INSERT INTO agenda_events (id,title,start_date,end_date,start_time,end_time,location_name,location_address,summary,description,image_key,status,source_kind,bulletin_id,bulletin_item_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,'published','bulletin',?,?,?,?,?)").bind(id,draft.title,draft.startDate,draft.endDate||null,draft.startTime||null,draft.endTime||null,draft.location.name,draft.location.address||null,draft.summary||null,draft.description||null,draft.image||null,bulletinId,activity.id,timestamp,`${timestamp}#${crypto.randomUUID()}`);}
  private children(input:BulletinInput,bulletinId:string,timestamp:string){const q:D1PreparedStatement[]=[];for(const item of input.announcements)q.push(this.db.prepare('INSERT INTO bulletin_announcements (id,bulletin_id,title,content_json,image_key,agenda_event_id,sort_order) VALUES (?,?,?,?,?,?,?)').bind(item.id,bulletinId,item.title,JSON.stringify(item.content),item.image||null,item.agendaEventId||null,item.sortOrder));for(const item of input.monthActivities){const event=this.eventInsert(item,bulletinId,timestamp);if(event)q.push(event);q.push(this.db.prepare('INSERT INTO bulletin_activities (id,bulletin_id,text,start_date,end_date,agenda_event_id,sort_order,start_time,end_time,location_name,location_address,description) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').bind(item.id,bulletinId,item.text,item.startDate||null,item.endDate||null,item.agendaEventId||null,item.sortOrder,item.startTime||null,item.endTime||null,item.locationName||null,item.locationAddress||null,item.description||null));}for(const item of input.birthdays)q.push(this.db.prepare('INSERT INTO bulletin_birthdays (id,bulletin_id,name,date,source,member_id,sort_order) VALUES (?,?,?,?,?,?,?)').bind(item.id,bulletinId,item.name,item.date,item.source,item.memberId||null,item.sortOrder));for(const item of input.diaconalSchedule)q.push(this.db.prepare('INSERT INTO bulletin_diaconal_schedule (id,bulletin_id,date,responsible_json,sort_order) VALUES (?,?,?,?,?)').bind(item.id,bulletinId,item.date,JSON.stringify(item.responsible),item.sortOrder));for(const item of input.weeklyReadings)q.push(this.db.prepare('INSERT INTO bulletin_weekly_readings (id,bulletin_id,day,reference_text,bible_book,bible_chapter,bible_verse_start,bible_verse_end,sort_order) VALUES (?,?,?,?,?,?,?,?,?)').bind(item.id,bulletinId,item.day,item.referenceText,item.reference?.book||null,item.reference?.chapter||null,item.reference?.verseStart||null,item.reference?.verseEnd||null,item.sortOrder));for(const [index,block] of (input.additionalBlocks||[]).entries())q.push(this.db.prepare('INSERT INTO bulletin_blocks (id,bulletin_id,block_json,sort_order) VALUES (?,?,?,?)').bind(`block-${bulletinId}-${index}`,bulletinId,JSON.stringify(block),index));return q;}
  async create(raw:BulletinInput,actor:string){const input=normalizeBulletin({...raw,id:raw.id||`bulletin-${crypto.randomUUID()}`,slug:raw.slug||slugifyBulletin(raw.number,raw.date)}),{timestamp,version}=stamp(),id=input.id;const r=input.pastoral.bibleReference;const insert=this.db.prepare('INSERT INTO bulletins (id,number,slug,date,template_id,status,pastoral_title,pastoral_body_json,bible_book,bible_chapter,bible_verse_start,bible_verse_end,published_at,deleted_at,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,input.number,input.slug,input.date,input.templateId,input.status,input.pastoral.title,JSON.stringify(input.pastoral.body),r?.book||null,r?.chapter||null,r?.verseStart||null,r?.verseEnd||null,input.status==='published'?timestamp:null,input.status==='trashed'?timestamp:null,timestamp,version);try{await this.db.batch([insert,...this.children(input,id,timestamp),audit(this.db,actor,input.status==='published'?'publish':'create',id,timestamp,{number:input.number})]);}catch(error){if(isUnique(error))throw new BulletinNumberConflictError('Este número de boletim já está em uso.');throw error;}return this.find(id);}
  async update(id:string,raw:BulletinInput,expected:string,actor:string){const current=await this.parent(id),input=normalizeBulletin({...raw,id,slug:raw.slug||slugifyBulletin(raw.number,raw.date)}),{timestamp,version}=stamp(),r=input.pastoral.bibleReference;const action=current.status!==input.status?(input.status==='published'?'publish':input.status==='trashed'?'trash':current.status==='published'?'unpublish':'update'):'update';let result;try{result=await this.db.prepare('UPDATE bulletins SET number=?,slug=?,date=?,template_id=?,status=?,pastoral_title=?,pastoral_body_json=?,bible_book=?,bible_chapter=?,bible_verse_start=?,bible_verse_end=?,published_at=?,deleted_at=?,updated_at=? WHERE id=? AND updated_at=?').bind(input.number,input.slug,input.date,input.templateId,input.status,input.pastoral.title,JSON.stringify(input.pastoral.body),r?.book||null,r?.chapter||null,r?.verseStart||null,r?.verseEnd||null,input.status==='published'?(current.published_at||timestamp):null,input.status==='trashed'?(current.deleted_at||timestamp):null,version,id,expected).run();}catch(error){if(isUnique(error))throw new BulletinNumberConflictError('Este número de boletim já está em uso.');throw error;}if((result.meta.changes||0)!==1)throw new BulletinAdminConflictError('Este boletim foi alterado em outra sessão. Recarregue antes de salvar novamente.');await this.db.batch([this.db.prepare('DELETE FROM bulletin_announcements WHERE bulletin_id=?').bind(id),this.db.prepare('DELETE FROM bulletin_activities WHERE bulletin_id=?').bind(id),this.db.prepare('DELETE FROM bulletin_birthdays WHERE bulletin_id=?').bind(id),this.db.prepare('DELETE FROM bulletin_diaconal_schedule WHERE bulletin_id=?').bind(id),this.db.prepare('DELETE FROM bulletin_weekly_readings WHERE bulletin_id=?').bind(id),this.db.prepare('DELETE FROM bulletin_blocks WHERE bulletin_id=?').bind(id),...this.children(input,id,timestamp),audit(this.db,actor,action,id,timestamp,{number:input.number})]);return this.find(id);}
  async duplicate(id:string,actor:string){const source=await this.find(id),suggestion=await this.suggestions(),renew=(prefix:string)=>`${prefix}-${crypto.randomUUID()}`;const input:BulletinInput={...source,id:undefined,slug:undefined,number:suggestion.number,date:suggestion.date,status:'draft',publishedAt:undefined,deletedAt:undefined,pdf:undefined,announcements:source.announcements.map(i=>({...i,id:renew('announcement'),agendaEventId:undefined})),monthActivities:source.monthActivities.map(i=>({...i,id:renew('activity'),agendaEventId:undefined,publishToAgenda:false,agendaEventDraft:undefined})),birthdays:source.birthdays.map(i=>({...i,id:renew('birthday')})),diaconalSchedule:source.diaconalSchedule.map(i=>({...i,id:renew('diaconal')})),weeklyReadings:source.weeklyReadings.map(i=>({...i,id:renew('reading')}))};const created=await this.create(input,actor);await this.db.prepare("UPDATE admin_audit_log SET action='duplicate',metadata_json=? WHERE entity_type='bulletin' AND entity_id=? AND action='create'").bind(JSON.stringify({sourceId:id,number:created.number}),created.id).run();return created;}
}
