import { normalizeStudy,type StudyInput,type StudyPublication,type VersionedStudy } from '../domain/study.ts';
import { StudyAdminConflictError,StudyAdminNotFoundError,type StudyAdminRepository } from './StudyAdminRepository.ts';
import { studyFromRow,type StudyRow } from './D1StudyRepository.ts';

type PublicationRow={revision:number;source_updated_at:string;published_at:string;published_by:string;withdrawn_at:string|null;withdrawn_by:string|null};
const version=()=>`${new Date().toISOString()}#${crypto.randomUUID()}`;
const optional=<T>(value:T|null)=>value===null?undefined:value;
const isConcurrencyGuard=(error:unknown)=>String(error).includes('iprc-concurrency-conflict');
const concurrencyGuard=(db:D1Database)=>db.prepare("SELECT CASE WHEN changes()=1 THEN 1 ELSE json('iprc-concurrency-conflict') END AS ok");
const audit=(db:D1Database,actor:string,action:string,id:string,metadata={})=>db.prepare("INSERT INTO admin_audit_log(id,actor,action,entity_type,entity_id,timestamp,metadata_json) VALUES(?,?,?,?,?,?,?)").bind(`audit-${crypto.randomUUID()}`,actor,action,'study',id,new Date().toISOString(),JSON.stringify(metadata));
const publicationFromRow=(row:PublicationRow):StudyPublication=>({revision:row.revision,sourceUpdatedAt:row.source_updated_at,publishedAt:row.published_at,publishedBy:row.published_by,withdrawnAt:optional(row.withdrawn_at),withdrawnBy:optional(row.withdrawn_by)});

export class D1StudyAdminRepository implements StudyAdminRepository{
  private readonly db:D1Database;
  constructor(db:D1Database){this.db=db;}
  private async row(id:string){const row=await this.db.prepare('SELECT * FROM studies WHERE id=?').bind(id).first<StudyRow>();if(!row)throw new StudyAdminNotFoundError('Estudo não encontrado.');return row;}
  private async hydrate(row:StudyRow):Promise<VersionedStudy>{const publication=await this.db.prepare('SELECT revision,source_updated_at,published_at,published_by,withdrawn_at,withdrawn_by FROM study_publications WHERE study_id=? ORDER BY revision DESC LIMIT 1').bind(row.id).first<PublicationRow>();return{...studyFromRow(row),publication:publication?publicationFromRow(publication):undefined,hasUnpublishedChanges:Boolean(row.status==='published'&&publication&&!publication.withdrawn_at&&publication.source_updated_at!==row.updated_at)};}
  async list(){const {results}=await this.db.prepare('SELECT * FROM studies ORDER BY COALESCE(study_date,published_at) DESC,created_at DESC').all<StudyRow>();return Promise.all(results.map(row=>this.hydrate(row)));}
  async find(id:string){return this.hydrate(await this.row(id));}
  async create(raw:StudyInput,actor:string){const study=normalizeStudy({...raw,status:'draft'}),stamp=version();await this.db.batch([this.db.prepare('INSERT INTO studies(id,slug,title,summary,author,study_date,published_at,youtube_video_id,thumbnail,duration_seconds,editorial_content,transcript,transcript_source,transcript_status,references_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(study.id,study.slug,study.title,study.summary||null,study.author,study.studyDate||null,null,study.youtubeId,study.thumbnail,study.durationSeconds||null,study.editorialContent||'',study.transcript||'',study.transcriptSource||null,study.transcriptStatus||'unavailable',JSON.stringify(study.references),'draft',stamp,stamp),audit(this.db,actor,'create',study.id)]);return this.find(study.id);}
  async update(id:string,raw:StudyInput,expected:string,actor:string){const current=await this.row(id);if(current.updated_at!==expected)throw new StudyAdminConflictError('Este estudo foi alterado em outra sessão.');const study=normalizeStudy({...raw,id,status:current.status,slug:current.slug}),stamp=version();try{await this.db.batch([this.db.prepare('UPDATE studies SET title=?,summary=?,author=?,study_date=?,youtube_video_id=?,thumbnail=?,duration_seconds=?,editorial_content=?,transcript=?,transcript_source=?,transcript_status=?,references_json=?,updated_at=? WHERE id=? AND updated_at=?').bind(study.title,study.summary||null,study.author,study.studyDate||null,study.youtubeId,study.thumbnail,study.durationSeconds||null,study.editorialContent||'',study.transcript||'',study.transcriptSource||null,study.transcriptStatus||'unavailable',JSON.stringify(study.references),stamp,id,expected),concurrencyGuard(this.db),audit(this.db,actor,'update',id,{status:current.status})]);}catch(error){if(isConcurrencyGuard(error))throw new StudyAdminConflictError('Este estudo foi alterado em outra sessão.');throw error;}return this.find(id);}
  async publish(id:string,expected:string,actor:string){const current=await this.row(id);if(current.updated_at!==expected)throw new StudyAdminConflictError('Este estudo foi alterado em outra sessão.');const study=studyFromRow(current),timestamp=new Date().toISOString(),last=await this.db.prepare('SELECT COALESCE(MAX(revision),0) AS revision FROM study_publications WHERE study_id=?').bind(id).first<{revision:number}>(),revision=(last?.revision||0)+1,snapshot=normalizeStudy({...study,status:'published',publishedAt:current.published_at||timestamp});try{await this.db.batch([this.db.prepare('UPDATE study_publications SET withdrawn_at=?,withdrawn_by=? WHERE study_id=? AND withdrawn_at IS NULL').bind(timestamp,actor,id),this.db.prepare("UPDATE studies SET status='published',published_at=COALESCE(published_at,?) WHERE id=? AND updated_at=?").bind(timestamp,id,expected),concurrencyGuard(this.db),this.db.prepare('INSERT INTO study_publications(id,study_id,revision,snapshot_json,source_updated_at,published_at,published_by) VALUES(?,?,?,?,?,?,?)').bind(`study-publication-${crypto.randomUUID()}`,id,revision,JSON.stringify(snapshot),expected,timestamp,actor),audit(this.db,actor,revision===1?'publish':'republish',id,{revision})]);}catch(error){if(isConcurrencyGuard(error))throw new StudyAdminConflictError('Este estudo foi alterado em outra sessão.');throw error;}return this.find(id);}
  async changeStatus(id:string,status:'draft'|'archived',expected:string,actor:string){const current=await this.row(id);if(current.updated_at!==expected)throw new StudyAdminConflictError('Este estudo foi alterado em outra sessão.');const timestamp=new Date().toISOString(),stamp=version();try{await this.db.batch([this.db.prepare('UPDATE studies SET status=?,updated_at=? WHERE id=? AND updated_at=?').bind(status,stamp,id,expected),concurrencyGuard(this.db),this.db.prepare('UPDATE study_publications SET withdrawn_at=?,withdrawn_by=? WHERE study_id=? AND withdrawn_at IS NULL').bind(timestamp,actor,id),audit(this.db,actor,status==='archived'?'archive':'unpublish',id)]);}catch(error){if(isConcurrencyGuard(error))throw new StudyAdminConflictError('Este estudo foi alterado em outra sessão.');throw error;}return this.find(id);}
}
