export {};
import { bibleReferenceLabel,parseBibleReferencesInput } from '../domain/study';
type Json=Record<string,any>;
const q=<T=HTMLElement>(selector:string)=>document.querySelector(selector) as T;
const dialog=q<HTMLDialogElement>('#study-editor'),form=q<HTMLFormElement>('#study-form');
let studies:Json[]=[],current:Json|null=null,timer:number|undefined,busy=false,trigger:HTMLElement|null=null;
const api=async(path:string,options:RequestInit={})=>{const response=await fetch(path,{...options,headers:{'content-type':'application/json',...(options.headers||{})}}),body=await response.json() as Json;if(!response.ok){const error=new Error(body.error?.message||'Operação indisponível.') as Error&{status?:number};error.status=response.status;throw error;}return body.data;};
const val=(id:string)=>q<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>(id).value;
const setReferenceErrors=(messages:string[])=>{const target=q('#study-reference-errors');target.replaceChildren(...messages.map(message=>{const line=document.createElement('span');line.textContent=message;return line;}));target.hidden=!messages.length;};
const parsedReferences=()=>{const parsed=parseBibleReferencesInput(val('#study-references'));setReferenceErrors(parsed.errors.map(error=>error.message));if(parsed.errors.length)throw new Error(parsed.errors[0].message);return parsed.references;};
const value=()=>({...(current?.id?{id:current.id,slug:current.slug}:{}),title:val('#study-title'),studyDate:val('#study-date')||undefined,author:val('#study-author'),youtubeUrl:val('#study-youtube'),thumbnail:val('#study-thumbnail')||undefined,durationSeconds:+val('#study-duration')||undefined,summary:val('#study-summary')||undefined,editorialContent:val('#study-content'),transcript:val('#study-transcript'),transcriptSource:val('#study-transcript-source')||undefined,transcriptStatus:val('#study-transcript-status'),references:parsedReferences(),status:current?.status||'draft'});
const setValue=(id:string,value:unknown)=>{q<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>(id).value=value==null?'':String(value);};
const publicationState=()=>{
  const target=q('#study-publication-status'),publish=q<HTMLButtonElement>('#study-publish'),unpublish=q<HTMLButtonElement>('#study-unpublish'),archive=q<HTMLButtonElement>('#study-archive'),restore=q<HTMLButtonElement>('#study-restore');
  delete target.dataset.pending;publish.disabled=false;publish.hidden=false;
  if(current?.status==='published'){
    publish.textContent=current.hasUnpublishedChanges?'Republicar':'Publicado';publish.disabled=!current.hasUnpublishedChanges;unpublish.hidden=false;archive.hidden=false;restore.hidden=true;
    target.textContent=current.hasUnpublishedChanges?`Publicado · revisão ${current.publication?.revision||1} · Alterações não publicadas`:`Publicado · revisão ${current.publication?.revision||1}`;
    if(current.hasUnpublishedChanges)target.dataset.pending='true';
  }else if(current?.status==='archived'){
    target.textContent='Arquivado';publish.hidden=true;unpublish.hidden=true;archive.hidden=true;restore.hidden=false;
  }else{
    target.textContent=current?.publication?'Despublicado · alterações privadas':'Rascunho';publish.textContent=current?.publication?'Publicar novamente':'Publicar';publish.hidden=false;unpublish.hidden=true;archive.hidden=false;restore.hidden=true;
  }
};
const fill=(study:Json,source?:HTMLElement)=>{
  current=study;trigger=source||trigger;
  for(const [id,entry] of [['#study-title',study.title],['#study-date',study.studyDate],['#study-author',study.author||'Presb. Maurício Buraseska'],['#study-youtube',study.youtubeUrl],['#study-thumbnail',study.thumbnail],['#study-duration',study.durationSeconds],['#study-summary',study.summary],['#study-content',study.editorialContent],['#study-transcript',study.transcript],['#study-transcript-source',study.transcriptSource],['#study-transcript-status',study.transcriptStatus||'unavailable'],['#study-references',(study.references||[]).map(bibleReferenceLabel).join('\n')]])setValue(id,entry);
  setReferenceErrors([]);
  q('#study-heading').textContent=study.id?study.title:'Novo estudo';q('#study-save-status').textContent=study.id?'Todas as alterações salvas':'Ainda não salvo';publicationState();render();if(!dialog.open)dialog.showModal();window.setTimeout(()=>q<HTMLInputElement>('#study-title').focus(),0);
};
const closeEditor=()=>{window.clearTimeout(timer);dialog.close();current=null;const editing=document.querySelector<HTMLElement>('.study-admin-card[data-editing=true]'),focusTarget=trigger;if(editing)editing.dataset.editing='false';trigger=null;window.setTimeout(()=>focusTarget?.focus(),50);};
const render=()=>{const target=q('#study-list');target.replaceChildren();for(const study of studies){const card=document.createElement('article'),image=document.createElement('img'),copy=document.createElement('div'),state=document.createElement('p'),heading=document.createElement('h2'),author=document.createElement('p'),edit=document.createElement('button');card.className='study-admin-card';card.dataset.editing=String(current?.id===study.id);image.src=study.thumbnail;image.alt='';state.textContent=study.status==='published'?(study.hasUnpublishedChanges?'Publicado · alterações pendentes':'Publicado'):study.status==='archived'?'Arquivado':'Rascunho';heading.textContent=study.title;author.textContent=study.author;copy.appendChild(state);copy.appendChild(heading);copy.appendChild(author);edit.className='admin-secondary';edit.type='button';edit.textContent='Editar';edit.addEventListener('click',()=>fill(study,edit));card.appendChild(image);card.appendChild(copy);card.appendChild(edit);target.appendChild(card);}};
const load=async()=>{try{const [session,items]=await Promise.all([api('/api/admin/session'),api('/api/admin/studies')]);q('#study-session').textContent=`Acesso confirmado para ${session.email}`;studies=items;render();}catch(error){q('#study-session').textContent='Não foi possível confirmar o acesso';const feedback=q('#study-feedback');feedback.textContent=error instanceof Error?error.message:'Falha ao carregar os estudos.';feedback.hidden=false;feedback.dataset.kind='error';}};
const refresh=async()=>{studies=await api('/api/admin/studies');if(current?.id)current=studies.find(item=>item.id===current?.id)||current;render();publicationState();};
const save=async(manual=false)=>{if(busy)return current;busy=true;window.clearTimeout(timer);try{const saved=current?.id?await api(`/api/admin/studies/${current.id}`,{method:'PUT',body:JSON.stringify({value:value(),expectedVersion:current.updatedAt})}):await api('/api/admin/studies',{method:'POST',body:JSON.stringify(value())});current=saved;q('#study-heading').textContent=saved.title;q('#study-save-status').textContent=manual?'Salvo agora':'Alterações salvas automaticamente';await refresh();return current;}catch(error){q('#study-save-status').textContent=error instanceof Error?error.message:'Falha ao salvar';return null;}finally{busy=false;}};
const schedule=()=>{q('#study-save-status').textContent='Alterações pendentes…';if(current?.status==='published'){current.hasUnpublishedChanges=true;publicationState();}window.clearTimeout(timer);timer=window.setTimeout(()=>save(false),1400);};
const action=async(name:'publish'|'unpublish'|'archive'|'restore')=>{const saved=await save(true);if(!saved)return;try{current=await api(`/api/admin/studies/${saved.id}/${name}`,{method:'POST',body:JSON.stringify({expectedVersion:saved.updatedAt})});q('#study-save-status').textContent=name==='publish'?'Versão pública atualizada':'Status atualizado';await refresh();}catch(error){q('#study-save-status').textContent=error instanceof Error?error.message:'Falha ao alterar status';}};

q('#new-study').addEventListener('click',event=>fill({title:'',author:'Presb. Maurício Buraseska',youtubeUrl:'',references:[],status:'draft'},event.currentTarget as HTMLElement));q('#study-close').addEventListener('click',closeEditor);dialog.addEventListener('cancel',event=>{event.preventDefault();closeEditor();});dialog.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();closeEditor();}});q('#study-save').addEventListener('click',()=>save(true));form.addEventListener('input',schedule);q('#study-references').addEventListener('input',()=>{const parsed=parseBibleReferencesInput(val('#study-references'));setReferenceErrors(parsed.errors.map(error=>error.message));});q('#study-publish').addEventListener('click',()=>action('publish'));q('#study-unpublish').addEventListener('click',()=>action('unpublish'));q('#study-archive').addEventListener('click',()=>action('archive'));q('#study-restore').addEventListener('click',()=>action('restore'));q('#study-preview').addEventListener('click',()=>{if(current?.slug)window.open(`https://iprc-2-backend-preview.iprc-2.workers.dev/estudos/${current.slug}`,'_blank','noopener');});load();
