export {};
import { bibleBooks, bibleReferenceLabel, type BibleReference } from '../domain/study';
type Json=Record<string,any>;
const q=(selector:string)=>document.querySelector(selector) as HTMLElement;
const slug=new URLSearchParams(location.search).get('slug')||location.pathname.split('/').filter(Boolean).at(-1)||'';
const format=(value:string)=>new Intl.DateTimeFormat('pt-BR',{timeZone:'UTC',day:'2-digit',month:'long',year:'numeric'}).format(new Date(`${value}T00:00:00Z`));
const inline=(parent:HTMLElement,parts:Json[]=[])=>parts.forEach(part=>{let node:Node=document.createTextNode(String(part.text||''));for(const mark of part.marks||[]){const wrapper=document.createElement(mark==='bold'?'strong':mark==='italic'?'em':'u');wrapper.appendChild(node);node=wrapper;}parent.appendChild(node);});
const rich=(target:HTMLElement,doc:Json)=>{target.replaceChildren();for(const block of doc?.blocks||[]){if(block.type==='list'){const list=document.createElement(block.style==='numbered'?'ol':'ul');for(const item of block.items||[]){const li=document.createElement('li');inline(li,item);list.appendChild(li);}target.appendChild(list);continue;}const element=document.createElement(block.type==='heading'?`h${block.level||3}`:block.type==='quote'?'blockquote':'p');inline(element,block.content);target.appendChild(element);}};
const setReference=(button:HTMLElement,reference:BibleReference,label=bibleReferenceLabel(reference))=>{const book=bibleBooks[reference.book];if(!book)return false;button.dataset.bibleReference='';button.dataset.book=book.slug;button.dataset.code=book.code;button.dataset.chapter=String(reference.chapter);button.dataset.start=String(reference.verseStart);button.dataset.end=String(reference.verseEnd||reference.verseStart);button.dataset.label=label;button.textContent=label;return true;};
const readingAliases:Record<string,string>={mt:'mateus',jo:'joao',sl:'salmos'};
const parseReadingPart=(value:string):Array<{label:string;reference:BibleReference}>=>{const cross=value.trim().match(/^([1-3]?\s?[A-Za-zÀ-ÿ]+)\s+(\d+)[.:](\d+)\s+a\s+(\d+)[.:](\d+)$/i);if(cross){const book=readingAliases[cross[1].toLowerCase().replace(/\s/g,'')];return book?[{label:`${cross[1]} ${cross[2]}.${cross[3]}`,reference:{book,chapter:+cross[2],verseStart:+cross[3]}},{label:`${cross[1]} ${cross[4]}.${cross[5]}`,reference:{book,chapter:+cross[4],verseStart:+cross[5]}}]:[];}const match=value.trim().match(/^([1-3]?\s?[A-Za-zÀ-ÿ]+)\s+(\d+)(?:[.:](\d+))?(?:[-–](\d+))?$/i);if(!match)return[];const book=readingAliases[match[1].toLowerCase().replace(/\s/g,'')];if(!book)return[];return[{label:value.trim(),reference:{book,chapter:+match[2],verseStart:match[3]?+match[3]:1,...(match[4]?{verseEnd:+match[4]}:!match[3]?{verseEnd:999}:{})}}];};
const appendReading=(item:Json,list:HTMLElement)=>{const li=document.createElement('li');li.appendChild(document.createTextNode(`${item.day}: `));if(item.reference&&bibleBooks[item.reference.book]){const button=document.createElement('button');button.type='button';button.className='inline-bible-reference';setReference(button,item.reference,item.referenceText||bibleReferenceLabel(item.reference));li.appendChild(button);list.appendChild(li);return;}const parts=String(item.referenceText||'').split(/\s+e\s+/i),parsed=parts.flatMap(parseReadingPart);if(!parsed.length){li.appendChild(document.createTextNode(item.referenceText));list.appendChild(li);return;}parsed.forEach((entry,index)=>{if(index)li.appendChild(document.createTextNode(parts.length>1?' e ':' a '));const button=document.createElement('button');button.type='button';button.className='inline-bible-reference';setReference(button,entry.reference,entry.label);li.appendChild(button);});list.appendChild(li);};
fetch(`/api/public/bulletins/${encodeURIComponent(slug)}`).then(async response=>{
  if(!response.ok)throw new Error();const bulletin=(await response.json() as Json).data;
  q('[data-title]').textContent=bulletin.pastoral.title;q('[data-edition]').textContent=`Boletim nº ${bulletin.number}`;q('[data-date]').textContent=format(bulletin.date);q('[data-date]').setAttribute('datetime',bulletin.date);
  if(bulletin.pastoral.bibleReference){const button=q('[data-reference]');if(setReference(button,bulletin.pastoral.bibleReference))button.hidden=false;}
  rich(q('[data-pastoral]'),bulletin.pastoral.body);
  const announcements=q('[data-announcements]');for(const item of bulletin.announcements){const article=document.createElement('article'),title=document.createElement('h3'),content=document.createElement('div');title.textContent=item.title;rich(content,item.content);article.appendChild(title);article.appendChild(content);announcements.appendChild(article);}q('[data-announcements-section]').hidden=!bulletin.announcements.length;
  const activities=q('[data-activities]');for(const item of bulletin.monthActivities){const li=document.createElement('li');li.textContent=item.text;activities.appendChild(li);}q('[data-activities-section]').hidden=!bulletin.monthActivities.length;
  const readings=q('[data-readings]');for(const item of bulletin.weeklyReadings)appendReading(item,readings);q('[data-readings-section]').hidden=!bulletin.weeklyReadings.length;
  const diaconal=q('[data-diaconal]');for(const item of bulletin.diaconalSchedule){const li=document.createElement('li');li.textContent=`${format(item.date)} — ${(item.responsible||[]).join(', ')}`;diaconal.appendChild(li);}q('[data-diaconal-section]').hidden=!bulletin.diaconalSchedule.length;
  const publicBirthdays=(bulletin.birthdays||[]).filter((item:Json)=>item.visibility==='public'),birthdays=q('[data-birthdays]');for(const item of publicBirthdays){const li=document.createElement('li');li.textContent=`${item.name} — ${format(item.date)}`;birthdays.appendChild(li);}q('[data-birthdays-section]').hidden=!publicBirthdays.length;
  q('[data-content]').hidden=false;document.title=`${bulletin.pastoral.title} — Boletim nº ${bulletin.number} — IPRC`;
}).catch(()=>{q('[data-title]').textContent='Boletim não encontrado';q('[data-error]').hidden=false;});
