/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 88e5248b725568130337864601b2999c)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker/index");
	}
	interface PreviewEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
	}
	interface ProductionEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
