/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 296ab11fece4ae49eeeb3f0e4af7d41f)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	ADMIN_ORIGIN?: "https://iprc-2-admin-preview.iprc-2.workers.dev";
}
declare namespace Cloudflare {
	interface PreviewEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		ADMIN_ORIGIN: "https://iprc-2-admin-preview.iprc-2.workers.dev";
	}
	interface ProductionEnv {
		MEDIA: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ADMIN_ORIGIN">> {}
}
